# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Agri-Hub. AI and Earth Observation for Sustainable Land Ecosystems research group.
email: agrihub.noa@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  AgriHUB is a research group within the Beyond Center of Earth Observation Research of the National Observatory of Athens.
  We conduct research in the domain of Big Earth data and Artificial Intelligence trying to understand agro-ecosystems 
  and develop applications which support sustainable and resilient agriculture.
  Over the last ten years, our team has participated in more than ten EU-funded projects providing agricultural information 
  services that utilize satellite data, drone images, street-level images, geotagged photos from the field 
  and numerical weather predictions to address real-world problems.
domain: agri-hub.github.io
url: "https://agri-hub.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
twitter_username: beyond_center
github_username:  agri-hub
github: [metadata]

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
# theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
